name: test-pyenv-multiuser
on: [push]
jobs:
    test-multiuser-setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  path: pyenv-multiuser
                  ref: testing
            - name: Setup base pyenv
              uses: actions/checkout@v2
              with:
                  repository: pyenv/pyenv
                  path: pyenv
            - uses: actions/setup-npm@v1
            - run: npm install -g bats
            - name: Setup testing workspace
              run: cp -r $GITHUB_WORKSPACE/pyenv $GITHUB_WORKSPACE/pyenv-test
              run: export PYENV_ROOT="$GITHUB_WORKSPACE/pyenv-test"
              run: export PYENV_BASE="$GITHUB_WORKSPACE/pyenv"
              run: mkdir /tmp/test_home
              run: cp -r $GITHUB_WORKSPACE/pyenv-multiuser $PYENV_ROOT/plugins/
            - name: execute pyenv-multiuser tests
              run: cd $PYENV_ROOT/plugins/pyenv-multiuser
              run: bats --tap test
