# This is a basic workflow to help you get started with Actions

name: test-branch-pyenv-multiuser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: pyenv-multiuser
          submodules: true
      
      - name: Setup base pyenv
        uses: actions/checkout@v2
        with:
          repository: pyenv/pyenv
          path: pyenv
          
      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0
        
      - name: Setup testing workspace
        run: |
          cp -r $GITHUB_WORKSPACE/pyenv $GITHUB_WORKSPACE/pyenv-test
          export PYENV_ROOT="$GITHUB_WORKSPACE/pyenv-test"
          export PYENV_BASE="$GITHUB_WORKSPACE/pyenv"
          mkdir /tmp/test_home
          cp -r $GITHUB_WORKSPACE/pyenv-multiuser $PYENV_ROOT/plugins/
          
      - name: execute pyenv-multiuser tests
        run: |
          export PYENV_ROOT="$GITHUB_WORKSPACE/pyenv-test"
          export PYENV_BASE="$GITHUB_WORKSPACE/pyenv"
          echo "PYENV_ROOT: '$PYENV_ROOT' PYENV_BASE: '$PYENV_BASE'"
          bats --tap $PYENV_ROOT/plugins/pyenv-multiuser/test
